spring: 
    profiles: 
        active: 
        - dev
---
spring:
    profiles: dev
    application: 
        name: microservicecloud-config-atguigu-dev
abb: 
  abc: 123
---
spring: 
    profiles: test
    application:
        name: microservicecloud-config-atguigu-test
