spring:
    profiles: {active: [dev]}
eureka:
    client: {service-url: {defaultZone: 'http://localhost:7001/eureka/'},register-with-eureka: false,fetch-registry: false}
    instance:
     hostname: eureka7001

server: 
  port: 7001
 
